<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Huuray.Examples.ReconcileAfterTimeout</RootNamespace>
    <AssemblyName>ReconcileAfterTimeout</AssemblyName>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Huuray/Huuray.csproj" />
  </ItemGroup>

</Project>
